#!/usr/bin/python
import sys
from math import ceil

if len(sys.argv) < 2:
	print "Usage: %s <filenames>" % sys.argv[0]
	exit()

ma = 0
for fn in sys.argv[1:]:
	f = open(fn).readlines()
	for line in f:
		a, b, val, t = line.replace("\n", "").split(" ")
		ma = max(ma, float(t))


print 1.5*ma


