#!/bin/bash
set -e

l="CLOCK LRU LFU ARC OPT"
l="OPT CLOCK LRU LFU ARC"
ss="50 100 250 500 1000 2500 5000 10000"
ss="10 25 50 75 100 250" 

if [[ ! -f $1 ]] 
then
	echo "Trace file $1 does not exist"
	exit
fi

for alg in $l 
do 
	parallel -i python sim.py $alg $1 {} >> "results/$alg.restmp" -- $ss
	sort -k2n,2 "results/$alg.restmp"  > "results/$alg.res"
	rm "results/$alg.restmp"
done 

